name: Lint and Unit Test
on: [pull_request]
jobs:
  lintunittesting:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Unit testing
        env:
          FORCE_COLOR: true
        run: |
          yarn test --coverage --ci
